<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">
	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<RazorLangVersion>3.0</RazorLangVersion>
		<BlazorEnableTimeZoneSupport>false</BlazorEnableTimeZoneSupport>
	</PropertyGroup>
	<ItemGroup>
		<EmbeddedResource Include="Resources\ar-SY.yml" />
		<EmbeddedResource Include="Resources\de-DE.yml" />
		<EmbeddedResource Include="Resources\en-US.yml" />
		<EmbeddedResource Include="Resources\es-ES.yml" />
		<EmbeddedResource Include="Resources\fa-IR.yml" />
		<EmbeddedResource Include="Resources\fr-FR.yml" />
		<EmbeddedResource Include="Resources\it-IT.yml" />
		<EmbeddedResource Include="Resources\pt-PT.yml" />
		<EmbeddedResource Include="Resources\ru-RU.yml" />
		<EmbeddedResource Include="Resources\tr-TR.yml" />
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="AKSoftware.Localization.MultiLanguages" Version="3.0.1" />
		<PackageReference Include="Blazored.Typeahead" Version="4.7.0" />
		<PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="8.0.8" />
		<PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="8.0.8" />
		<PackageReference Include="Microsoft.Authentication.WebAssembly.Msal" Version="8.0.8" />
		<PackageReference Include="Microsoft.Extensions.Http" Version="8.0.0" />
		<PackageReference Include="Microsoft.FluentUI.AspNetCore.Components" Version="4.10.0" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
		<PackageReference Include="System.Net.Http.Json" Version="8.0.0" />
		<PackageReference Include="Blazored.TextEditor" Version="1.1.0" />
	</ItemGroup>
	<ItemGroup>
	  <ProjectReference Include="..\Shared\sd.Shared.csproj" />
	</ItemGroup>
</Project>
