trigger:
- work

variables:
  buildConfiguration: 'Release'

stages:

# ---------- Build Stage ----------
- stage: Build
  displayName: 'Build Stage'
  jobs:
  - job: BuildProjects
    displayName: 'Server'
    pool:
      vmImage: 'windows-latest'

    steps:
    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        version: '8.0.x'

    - task: DotNetCoreCLI@2
      displayName: 'Restore Server'
      inputs:
        command: 'restore'
        projects: Server/sd.Api.csproj

    - task: DotNetCoreCLI@2
      displayName: 'Build Server'
      inputs:
        command: 'build'
        projects: 'Server/sd.Api.csproj'
        arguments: '--configuration $(buildConfiguration)'

    - task: DotNetCoreCLI@2
      displayName: 'Publish Server'
      inputs:
        command: 'publish'
        publishWebProjects: false
        projects: 'Server/sd.Api.csproj'
        arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/Server'
        zipAfterPublish: true

    - task: PublishBuildArtifacts@1
      inputs:
        pathToPublish: '$(Build.ArtifactStagingDirectory)/Server'
        artifactName: 'webapi'
        publishLocation: 'Container'

# ---------- Deploy WebAPI to Azure App Service ----------
- stage: Deploy_WebAPI
  displayName: 'Deploy WebAPI to Azure App Service'
  dependsOn: Build
  jobs:
  - deployment: DeployAPI
    displayName: 'Deploy API'
    environment: 'production'
    pool:
      vmImage: 'windows-latest'

    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: webapi

          - task: AzureWebApp@1
            displayName: 'Deploy WebAPI to App Service'
            inputs:
              azureSubscription: 'sdApi20200529140234'   # Replace with your actual service connection name
              appType: 'webApp'
              appName: 'sdApi20200529140234'
              package: '$(Pipeline.Workspace)/webapi/*.zip'
