<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">
  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <RazorLangVersion>3.0</RazorLangVersion>
    <BlazorEnableTimeZoneSupport>false</BlazorEnableTimeZoneSupport>
  </PropertyGroup>
	<ItemGroup>
		<PackageReference Include="Blazored.TextEditor" Version="1.1.0" />
		<PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="7.0.13" />
		<PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="7.0.13" PrivateAssets="all" />
	</ItemGroup>
  <ItemGroup>
    <Compile Remove="bin\**" />
    <Content Remove="bin\**" />
    <EmbeddedResource Remove="bin\**" />
    <None Remove="bin\**" />
  </ItemGroup>
  <ItemGroup>
    <None Remove="Resources\ar-SY.yml" />
    <None Remove="Resources\de-DE.yml" />
    <None Remove="Resources\en-US.yml" />
    <None Remove="Resources\es-ES.yml" />
    <None Remove="Resources\fa-IR.yml" />
    <None Remove="Resources\fr-FR.yml" />
    <None Remove="Resources\it-IT.yml" />
    <None Remove="Resources\pt-PT.yml" />
    <None Remove="Resources\ru-RU.yml" />
    <None Remove="Resources\tr-TR.yml" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\ar-SY.yml" />
    <EmbeddedResource Include="Resources\de-DE.yml" />
    <EmbeddedResource Include="Resources\en-US.yml" />
    <EmbeddedResource Include="Resources\es-ES.yml" />
    <EmbeddedResource Include="Resources\fa-IR.yml" />
    <EmbeddedResource Include="Resources\fr-FR.yml" />
    <EmbeddedResource Include="Resources\it-IT.yml" />
    <EmbeddedResource Include="Resources\pt-PT.yml" />
    <EmbeddedResource Include="Resources\ru-RU.yml" />
    <EmbeddedResource Include="Resources\tr-TR.yml" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="AKSoftware.Localization.MultiLanguages" Version="3.0.1" />
    <PackageReference Include="Blazored.Typeahead" Version="4.3.0" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="7.0.14" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="7.0.14" />
    <PackageReference Include="Microsoft.Authentication.WebAssembly.Msal" Version="7.0.14" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="8.0.0" />
    <PackageReference Include="System.Net.Http.Json" Version="8.0.0" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Properties\PublishProfiles\" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Shared\SD.Shared.csproj" />
  </ItemGroup>
</Project>