name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - work
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - work

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies (Client)
        run: dotnet restore ./Client/sd.Client.csproj

      - name: Restore dependencies (API)
        run: dotnet restore ./Server/sd.Api.csproj

      - name: Clean (Client)
        run: dotnet clean ./Client/sd.Client.csproj --configuration Release

      - name: Clean (API)
        run: dotnet clean ./Server/sd.Api.csproj --configuration Release

      - name: Build (Client)
        run: dotnet build ./Client/sd.Client.csproj --configuration Release --no-restore

      - name: Build (API)
        run: dotnet build ./Server/sd.Api.csproj --configuration Release --no-restore

      - name: Publish Client
        run: dotnet publish ./Client/sd.Client.csproj --configuration Release --output ./output/wwwroot --no-build

      - name: Publish API
        run: dotnet publish ./Server/sd.Api.csproj --configuration Release --output ./output/api --no-build

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_RED_POND_0CCF1D603 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # For PR comments
          action: "upload"
          app_location: "./output/wwwroot"       # Published client app
          api_location: "./output/api"           # Published API
          output_location: ""                    # Not needed when manually publishing

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_RED_POND_0CCF1D603 }}
          action: "close"
