name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - work
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - work

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
      - name: Build the Blazor WebAssembly app
        run: dotnet publish SD/Client -c Release -o build
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1.1.0
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_RED_POND_0CCF1D603 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "SD/Client"
          api_location: "SD/Api"
          output_location: "build/wwwroot"

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1.1.0
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_RED_POND_0CCF1D603 }}
          action: "close"
